name: Python package

on: [push]

jobs:
  build-and-test:
    name: Build and test for (${{ matrix.python-version }}, ubuntu-latest)
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install wheel pytorch and jax
        run: |
          python -m pip install --upgrade pip
          pip install pytest setuptools wheel
          pip install torch --index-url https://download.pytorch.org/whl/cpu
          pip install --upgrade "jax[cpu]"
      - name: Install package
        run: |
          pip install .
      - name: Test with pytest
        run: |
          pytest

  build-and-test:
    name: Build and test for (${{ matrix.python-version }}, ubuntu-latest)
    runs-on: 'macos-latest'
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install wheel pytorch and jax
        run: |
          python -m pip install --upgrade pip
          pip install pytest setuptools wheel
          pip install torch
          pip install --upgrade "jax[cpu]"
      - name: Install package
        run: |
          pip install .
      - name: Test with pytest
        run: |
          pytest
